/* eslint-disable max-len */
import React, { useEffect } from 'react';

const Content = () => {
  useEffect(() => {
    // console.log('<Content> Mounted');
  }, []);

  return (
    <div className="content">
      <h1>HEADLINE</h1>
      <hr className="content__divider" />
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque consequat tempus purus ac vulputate. Nunc volutpat tempus dui nec volutpat. Suspendisse mauris ante, pellentesque sed aliquam ut, facilisis eu erat. Maecenas eleifend ipsum sem, eget tempor eros egestas quis. Duis vulputate rhoncus ullamcorper. Fusce pretium fermentum magna vitae fringilla. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed diam sapien, molestie vitae dolor id, dignissim vestibulum est. Phasellus ac ipsum eget est dignissim pharetra ut sit amet sapien. Nunc quis risus eu ipsum egestas rutrum. Aenean nec pulvinar ante, non laoreet quam. Morbi luctus ex vitae vulputate porta. Cras pharetra molestie placerat.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque consequat tempus purus ac vulputate. Nunc volutpat tempus dui nec volutpat. Suspendisse mauris ante, pellentesque sed aliquam ut, facilisis eu erat. Maecenas eleifend ipsum sem, eget tempor eros egestas quis. Duis vulputate rhoncus ullamcorper. Fusce pretium fermentum magna vitae fringilla. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed diam sapien, molestie vitae dolor id, dignissim vestibulum est. Phasellus ac ipsum eget est dignissim pharetra ut sit amet sapien. Nunc quis risus eu ipsum egestas rutrum. Aenean nec pulvinar ante, non laoreet quam. Morbi luctus ex vitae vulputate porta. Cras pharetra molestie placerat.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque consequat tempus purus ac vulputate. Nunc volutpat tempus dui nec volutpat. Suspendisse mauris ante, pellentesque sed aliquam ut, facilisis eu erat. Maecenas eleifend ipsum sem, eget tempor eros egestas quis. Duis vulputate rhoncus ullamcorper. Fusce pretium fermentum magna vitae fringilla. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed diam sapien, molestie vitae dolor id, dignissim vestibulum est. Phasellus ac ipsum eget est dignissim pharetra ut sit amet sapien. Nunc quis risus eu ipsum egestas rutrum. Aenean nec pulvinar ante, non laoreet quam. Morbi luctus ex vitae vulputate porta. Cras pharetra molestie placerat.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque consequat tempus purus ac vulputate. Nunc volutpat tempus dui nec volutpat. Suspendisse mauris ante, pellentesque sed aliquam ut, facilisis eu erat. Maecenas eleifend ipsum sem, eget tempor eros egestas quis. Duis vulputate rhoncus ullamcorper. Fusce pretium fermentum magna vitae fringilla. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed diam sapien, molestie vitae dolor id, dignissim vestibulum est. Phasellus ac ipsum eget est dignissim pharetra ut sit amet sapien. Nunc quis risus eu ipsum egestas rutrum. Aenean nec pulvinar ante, non laoreet quam. Morbi luctus ex vitae vulputate porta. Cras pharetra molestie placerat.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque consequat tempus purus ac vulputate. Nunc volutpat tempus dui nec volutpat. Suspendisse mauris ante, pellentesque sed aliquam ut, facilisis eu erat. Maecenas eleifend ipsum sem, eget tempor eros egestas quis. Duis vulputate rhoncus ullamcorper. Fusce pretium fermentum magna vitae fringilla. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed diam sapien, molestie vitae dolor id, dignissim vestibulum est. Phasellus ac ipsum eget est dignissim pharetra ut sit amet sapien. Nunc quis risus eu ipsum egestas rutrum. Aenean nec pulvinar ante, non laoreet quam. Morbi luctus ex vitae vulputate porta. Cras pharetra molestie placerat.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque consequat tempus purus ac vulputate. Nunc volutpat tempus dui nec volutpat. Suspendisse mauris ante, pellentesque sed aliquam ut, facilisis eu erat. Maecenas eleifend ipsum sem, eget tempor eros egestas quis. Duis vulputate rhoncus ullamcorper. Fusce pretium fermentum magna vitae fringilla. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed diam sapien, molestie vitae dolor id, dignissim vestibulum est. Phasellus ac ipsum eget est dignissim pharetra ut sit amet sapien. Nunc quis risus eu ipsum egestas rutrum. Aenean nec pulvinar ante, non laoreet quam. Morbi luctus ex vitae vulputate porta. Cras pharetra molestie placerat.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque consequat tempus purus ac vulputate. Nunc volutpat tempus dui nec volutpat. Suspendisse mauris ante, pellentesque sed aliquam ut, facilisis eu erat. Maecenas eleifend ipsum sem, eget tempor eros egestas quis. Duis vulputate rhoncus ullamcorper. Fusce pretium fermentum magna vitae fringilla. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed diam sapien, molestie vitae dolor id, dignissim vestibulum est. Phasellus ac ipsum eget est dignissim pharetra ut sit amet sapien. Nunc quis risus eu ipsum egestas rutrum. Aenean nec pulvinar ante, non laoreet quam. Morbi luctus ex vitae vulputate porta. Cras pharetra molestie placerat.</p>
    </div>
  );
};

export default Content;
