export const ARTICLE_ADD_SUCCESS = 'ARTICLE_ADD_SUCCESS';
export const ARTICLE_ADD_FAILURE = 'ARTICLE_ADD_FAILURE';
export const ARTICLE_DELETE = 'ARTICLE_DELETE';

export const UPDATE_ACTION_RESULT_STATE = 'UPDATE_ACTION_RESULT_STATE';

export const UI_STATUS_UPDATE = 'UI_UPDATE_STATUS_REQUEST';
export const UI_STATUS_UPDATE_SUCCESS = 'UI_UPDATE_STATUS_SUCCESS';
